{
 ;time/period          time-literals.data-readers/period  #?(:cljs time-literals.data-readers-cljs/period           :clj )
 time/date             #?(:cljs time-literals.data-readers-cljs/date             :clj time-literals.data-readers/date)
 time/date-time        #?(:cljs time-literals.data-readers-cljs/date-time        :clj time-literals.data-readers/date-time)
 time/zoned-date-time  #?(:cljs time-literals.data-readers-cljs/zoned-date-time  :clj time-literals.data-readers/zoned-date-time)
 ;time/offset-time      #?(:cljs time-literals.data-readers-cljs/offset-time      :clj time-literals.data-readers/offset-time)
 time/instant          #?(:cljs time-literals.data-readers-cljs/instant          :clj time-literals.data-readers/instant)
 ;time/offset-date-time #?(:cljs time-literals.data-readers-cljs/offset-date-time :clj time-literals.data-readers/offset-date-time)
 ;time/zone             #?(:cljs time-literals.data-readers-cljs/zone             :clj time-literals.data-readers/zone)
 ;time/day-of-week      #?(:cljs time-literals.data-readers-cljs/day-of-week      :clj time-literals.data-readers/day-of-week)
 time/time             #?(:cljs time-literals.data-readers-cljs/time             :clj time-literals.data-readers/time)
 ;time/month            #?(:cljs time-literals.data-readers-cljs/month            :clj time-literals.data-readers/month)
 time/month-day        #?(:cljs time-literals.data-readers-cljs/month-day        :clj time-literals.data-readers/month-day)
 time/duration         #?(:cljs time-literals.data-readers-cljs/duration         :clj time-literals.data-readers/duration)
 ;time/year             #?(:cljs time-literals.data-readers-cljs/year             :clj time-literals.data-readers/year)
 time/year-month       #?(:cljs time-literals.data-readers-cljs/year-month       :clj time-literals.data-readers/year-month)
 }
