{
 time/period           #?(:cljs time-literals.data-readers-cljs/period           :clj time-literals.data-readers-clj/period)
 time/date             #?(:cljs time-literals.data-readers-cljs/date             :clj time-literals.data-readers-clj/date)
 time/date-time        #?(:cljs time-literals.data-readers-cljs/date-time        :clj time-literals.data-readers-clj/date-time)
 time/zoned-date-time  #?(:cljs time-literals.data-readers-cljs/zoned-date-time  :clj time-literals.data-readers-clj/zoned-date-time)
 time/offset-time      #?(:cljs time-literals.data-readers-cljs/offset-time      :clj time-literals.data-readers-clj/offset-time)
 time/instant          #?(:cljs time-literals.data-readers-cljs/instant          :clj time-literals.data-readers-clj/instant)
 time/offset-date-time #?(:cljs time-literals.data-readers-cljs/offset-date-time :clj time-literals.data-readers-clj/offset-date-time)
 time/zone             #?(:cljs time-literals.data-readers-cljs/zone             :clj time-literals.data-readers-clj/zone)
 time/day-of-week      #?(:cljs time-literals.data-readers-cljs/day-of-week      :clj time-literals.data-readers-clj/day-of-week)
 time/time             #?(:cljs time-literals.data-readers-cljs/time             :clj time-literals.data-readers-clj/time)
 time/month            #?(:cljs time-literals.data-readers-cljs/month            :clj time-literals.data-readers-clj/month)
 time/month-day        #?(:cljs time-literals.data-readers-cljs/month-day        :clj time-literals.data-readers-clj/month-day)
 time/duration         #?(:cljs time-literals.data-readers-cljs/duration         :clj time-literals.data-readers-clj/duration)
 time/year             #?(:cljs time-literals.data-readers-cljs/year             :clj time-literals.data-readers-clj/year)
 time/year-month       #?(:cljs time-literals.data-readers-cljs/year-month       :clj time-literals.data-readers-clj/year-month)
 }
