# https://practical.li/clojure/continuous-integration/github-actions/
name: Tests build
on: [push, pull_request]
jobs:
  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: 1.10.1.693 # Clojure CLI based on tools.deps
          
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest          

      - name: Run Clj Unit tests (jsjoda)
        run: make test-clj-jsjoda

      - name: Run Cljs Unit tests (jsjoda)
        run: make test-cljs-jsjoda
          
      - name: Run Clj Unit tests (temporal)
        run: make test-clj-temporal

      - name: Run Cljs Unit tests (temporal)
        run: make test-cljs-temporal          